//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iepDucan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareProduct
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Version { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
